# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        tennis: 3
        sports: 1
        swing: 1
        player: 1
        racket: 1
        shot: 1
        pose: 1
        object detection: 1
        tracking: 1
        action recognistion: 1
        action detection: 1
        event detection: 1


# 通知の閾値
score_threshold: 2
